# Generated by Django 5.2.5 on 2026-08-27 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathly', '0002_groupsaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsaves',
            name='places',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
